import { Router } from "express";
import {
  initializeOIDC,
  createAuthSession,
  getAuthorizationUrl,
  handleCallback,
  getUserInfo,
} from "../auth/oidc";
import { requireAuth, syncUser } from "../middleware/auth";
import type { AuthenticatedRequest } from "../types";

const router = Router();

// Initialize OIDC on first request
let oidcInitialized = false;

async function ensureOIDC() {
  if (!oidcInitialized) {
    await initializeOIDC();
    oidcInitialized = true;
  }
}

// GET /auth/login - Initiate OIDC login flow
router.get("/login", async (req, res) => {
  try {
    await ensureOIDC();

    const redirectUri = req.query.redirect_uri as string | undefined;
    const session = createAuthSession(redirectUri);
    req.session.oidc = session;

    const authorizationUrl = getAuthorizationUrl(session, redirectUri);
    res.redirect(authorizationUrl);
  } catch (error) {
    console.error("Login error:", error);
    res.status(500).json({ error: "Failed to initiate login" });
  }
});

// GET /auth/callback - OIDC callback handler
router.get("/callback", async (req, res) => {
  try {
    await ensureOIDC();

    const oidcSession = req.session.oidc;
    if (!oidcSession) {
      res.status(400).json({ error: "Invalid session" });
      return;
    }

    const tokenSet = await handleCallback(
      req.query as Record<string, string>,
      oidcSession,
    );
    const user = await getUserInfo(tokenSet);

    // Sync user with database
    await syncUser(user);

    // Store user in session
    req.session.user = user;
    delete req.session.oidc;

    // Redirect to frontend
    const frontendUrl = process.env.APP_URL || "http://localhost:5173";
    res.redirect(`${frontendUrl}/auth/callback?success=true`);
  } catch (error) {
    console.error("Callback error:", error);
    const frontendUrl = process.env.APP_URL || "http://localhost:5173";
    res.redirect(`${frontendUrl}/auth/callback?error=authentication_failed`);
  }
});

// POST /auth/logout - End session
router.post("/logout", (req: AuthenticatedRequest, res) => {
  req.session.destroy((err) => {
    if (err) {
      res.status(500).json({ error: "Failed to logout" });
      return;
    }
    res.clearCookie("connect.sid");
    res.json({ message: "Logged out successfully" });
  });
});

// GET /auth/me - Get current user
router.get("/me", requireAuth, (req: AuthenticatedRequest, res) => {
  res.json(req.user);
});

// POST /auth/token - Exchange authorization code for tokens (for native apps)
// The session cookie set during /auth/login is sent automatically by ASWebAuthenticationSession,
// so req.session.oidc contains the original state/nonce for validation.
router.post("/token", async (req, res) => {
  try {
    await ensureOIDC();

    const { code, state, code_verifier, redirect_uri } = req.body;

    if (!code || !state || !code_verifier || !redirect_uri) {
      res.status(400).json({ error: "Missing required parameters: code, state, code_verifier, redirect_uri" });
      return;
    }

    const oidcSession = req.session.oidc;
    if (!oidcSession) {
      res.status(400).json({ error: "No active OIDC session. Initiate login first." });
      return;
    }

    // Validate that the returned state matches what was stored in the session
    if (oidcSession.state !== state) {
      res.status(400).json({ error: "State mismatch" });
      return;
    }

    // Use the session's own codeVerifier (generated by the backend during /auth/login)
    // rather than a client-supplied one, to prevent verifier substitution attacks.
    const session = {
      codeVerifier: oidcSession.codeVerifier,
      state: oidcSession.state,
      nonce: oidcSession.nonce,
      redirectUri: redirect_uri,
    };

    const tokenSet = await handleCallback({ code, state }, session);

    const user = await getUserInfo(tokenSet);
    await syncUser(user);

    // Clear OIDC session state now that it has been consumed
    delete req.session.oidc;

    res.json({
      access_token: tokenSet.access_token,
      id_token: tokenSet.id_token,
      token_type: tokenSet.token_type,
      expires_in: tokenSet.expires_in,
      user,
    });
  } catch (error) {
    console.error("Token exchange error:", error);
    res.status(500).json({ error: "Failed to exchange token" });
  }
});

export default router;
